### ISSUE TITLE
garage._environment file not available

### ISSUE THREAD

**Issue by Rajwinders13** [rlworkgroup/garage#2187]
I am trying to run ddpg, in one of the python files there is import statement from garage._environment import Environment, EnvSpec, EnvStep, StepType 
But there is no file as _environment.py in garage, I saw somewhere there is import like from garage import Environment, EnvSpec, EnvStep, StepType but then import statements supporting these are also not present in the __init__.py 
Does someone knows the way around this?

**Comment by ryanjulian** [comment]
@Rajwinders13 did you fix your issue? If so, how?

**Comment by Rajwinders13** [comment]
@ryanjulian

**Comment by ryanjulian** [comment]
Can you give us a short script to reproduce your problem?

**Comment by Rajwinders13** [comment]
I ran the following import statements:

import tensorflow as tf

from garage import wrap_experiment
from garage import GymEnv
from garage.experiment.deterministic import set_seed
from garage.np.exploration_policies import AddOrnsteinUhlenbeckNoise
from garage.replay_buffer import PathBuffer
from garage.tf.algos import DDPG
from garage.tf.policies import ContinuousMLPPolicy
from garage.tf.q_functions import ContinuousMLPQFunction
from garage.trainer import TFTrainer

And the very first error that I get is: ImportError: cannot import name 'GymEnv' from 'garage' 
I fixed this by making changes to the __init__.py file, but then there were some more issues with other import statements, I am trying to run the sample tensor flow code sample of ddpg given in the documentation.
I installed the library using pip install garage but it does not installs the complete directory and just the inner garage directory.

**Comment by krzentner** [comment]
It's quite likely this issue is due to installing garage from pip (which is fairly old at this point, we plan to do a new release soon), and using example files from master. If you clone the repo and `pip install .` inside it do you still have these problems?

**Comment by seongwonlee111** [comment]
@krzentner I had a same problem, and I was able to solve this problem by doing `pip install .` inside the repo.
Thanks a lot!

**Comment by PorkShoulderHolder** [comment]
Was the pip install process ever fixed?  I'm still having this error now.

**Comment by krzentner** [comment]
We have released a new version of garage since then, and updating should fix the issue. Alternatively, you can use examples from the previous release branch.
