### ISSUE TITLE
Use tf.variable_scope instead of tf.VariableScope for policies using models

### ISSUE THREAD

**Issue by zhanpenghe** [rlworkgroup/garage#609]
Using `tf.VariableScope` will not add a new scope to the graph. This introduces bugs to `model.parameters`.

**Comment by ahtsan** [comment]
When the first time `model.build()` is called, it creates a new `tf.variable_scope` by doing
```python
    ...
    if not self._networks:
            with tf.variable_scope(
                    self._name, reuse=False) as self._variable_scope:
   ...
```
and store the `tf.VariableScope` for reentering.
Which part are you referring to?

**Comment by zhanpenghe** [comment]
Sorry I think I am referring to policies with models.
https://github.com/rlworkgroup/garage/blob/d8c279e1573ab16fa4c9ba7a89a0cc5012f0caac/garage/tf/policies/base2.py#L17

**Comment by ryanjulian** [comment]
@ahtsan can you please take a look?

**Comment by ahtsan** [comment]
It's resolved by #606 by
https://github.com/rlworkgroup/garage/blob/274566e491d5c7157f3c8deff136c56838022349/garage/tf/policies/base2.py#L17
The issue is not that we used `tf.VariableScope`, but we missed the `reuse` constructor argument. We should do `tf.VariableScope(reuse=False, name=name)` but we did `tf.VariableScope(name)`.
(Reference: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/variable_scope.py#L1044)

**Comment by zhanpenghe** [comment]
Oh sorry for not elaborating on this. In order to reproduce this problem, you can try to retrieve the model (actually policy) parameters. If this is returning parameters from other models (e.g baseline) then this flaw is still present. 

The real flaw is that is doesn't actually create a variable scope so I don't think adding reuse will resolve it.
@ahtsan

**Comment by ahtsan** [comment]
TensorFlow suggested this for variable_scope reentering:
```python
with tf.variable(name=name) as self._variable_scope:
    ....

#reenter
with tf.variable_scope(self._variable_scope):
    ...
```

https://github.com/tensorflow/tensorflow/blob/r1.13/tensorflow/python/ops/variable_scope.py#L1985
